Added ability to pass username at runtime

diff --git a/pkgwatch b/pkgwatch
--- a/pkgwatch
+++ b/pkgwatch
@@ -1,10 +1,11 @@
 #!/bin/bash
 #
-# pkgwatch v0.3 - Arch out of date package notifier.
+# pkgwatch v0.4 - Arch out of date package notifier.
 # Copyright (C) 2009 Daniel J Griffiths <ghost1227@archlinux.us>
 # Thanks to:
 #            Wonder & Louipc for the initial idea
 #            Rson for helping track down the bugs in 0.2
+#                 and submitting a good bit of code cleanup
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,26 +22,18 @@
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 # 02110-1301, USA.
 
-VER=0.1
-OPT="none"
+VER=0.4
+NOTIFY=0
 INFO="\e[1;33m==>\e[1;37m"
 ERROR="\e[1;31m==>\e[1;37m"
 SUCCESS="\e[1;32m==>\e[1;37m"
 RESET="\e[0m"
 
+unset USER
+
 if [ -f /tmp/pkgwatch ]; then
 	rm -f /tmp/pkgwatch
 fi
-
-if [ ! -f $HOME/.config/pkgwatch/config ]; then
-	if [ ! -d $HOME/.config/pkgwatch ]; then
-		mkdir $HOME/.config/pkgwatch
-	fi
-	echo -e "# Configuration for pkgwatch is simple. Set USER to your AUR username.\n\nUSER=" > $HOME/.config/pkgwatch/config
-	echo -e "$ERROR Please edit $HOME/.config/pkgwatch/config before continuing!$RESET"
-	exit 0
-fi
-
 
 ##############################
 ### VERSION FUNCTION       ###
@@ -65,11 +58,16 @@ usage() {
 ### GET FUNCTION           ###
 ##############################
 get() {
-	source $HOME/.config/pkgwatch/config
+	if [ -z $USER ]; then
+		if [ -f $HOME/.config/pkgwatch/config ]; then
+			source $HOME/.config/pkgwatch/config
+		fi
+	fi
 
 	if [ -z $USER ]; then
 		echo -e "$ERROR Missing configuration information!"
-		echo -e "$ERROR Please edit $HOME/.config/pkgwatch/config$RESET"
+		echo -e "$ERROR Please pass a username or set \"USER=username\" in $HOME/.config/pkgwatch/config$RESET"
+		exit 1
 	fi
 
 	TOTAL=`wget -q -O - "http://aur.archlinux.org/packages.php?O=0&K=$USER&do_Search=Go&detail=1&L=2&C=0&SeB=m&SB=n&SO=a&PP=100&outdated=on" | grep "Showing results" | awk '{ print $7}'`
@@ -97,8 +95,8 @@ get() {
 		done
 	fi
 
-	if [ $OPT = "n" ]; then
-		OOD=`cat /tmp/pkgwatch`
+	if [ $NOTIFY -eq 1 ]; then
+		OOD=$(< /tmp/pkgwatch)
 		notify-send "Out of date packages:" "$OOD"
 	else
 		echo -e "$INFO The following packages are marked out of date:"
@@ -115,8 +113,7 @@ get() {
 while [ "$#" -ne "0" ]; do
 	case $1 in
 		'-n'|'--notify')
-		OPT="n"
-		get
+		let NOTIFY=1
 		;;
 		'-h'|'--help')
 		usage
@@ -127,8 +124,7 @@ while [ "$#" -ne "0" ]; do
 		exit 0
 		;;
 		*)
-		get
-		exit 0
+		USER=$1
 		;;
 	esac
 	shift
